// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxV7h7QDnZLNu-24up0JZ5pWHV_sZ13p8',
    appId: '1:1073609177555:web:c2144f1789aeb0c8f75726',
    messagingSenderId: '1073609177555',
    projectId: 'login-41d34',
    authDomain: 'login-41d34.firebaseapp.com',
    storageBucket: 'login-41d34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQSPx-jzSJqi7o93DbrvU3zO9kvCLGcg',
    appId: '1:1073609177555:android:8e4534d541603ea4f75726',
    messagingSenderId: '1073609177555',
    projectId: 'login-41d34',
    storageBucket: 'login-41d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSEZUQO17bMtMHvPWas0V3oGgRewN-JM',
    appId: '1:1073609177555:ios:16cc168250d5460ef75726',
    messagingSenderId: '1073609177555',
    projectId: 'login-41d34',
    storageBucket: 'login-41d34.appspot.com',
    iosBundleId: 'com.example.kopimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSEZUQO17bMtMHvPWas0V3oGgRewN-JM',
    appId: '1:1073609177555:ios:16cc168250d5460ef75726',
    messagingSenderId: '1073609177555',
    projectId: 'login-41d34',
    storageBucket: 'login-41d34.appspot.com',
    iosBundleId: 'com.example.kopimate',
  );
}
